name: HACS Validation

on: [push]

jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
